<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if (!$block->isContentMode() || $block->isMixedMode()) :?>
    <?= $block->getProductListHtml() ?>
    <div class="bg-red-500  mob:bg-pink-200  md:bg-green-500 lg:bg-blue-500 p-10 font-bold">
        TEST
    </div>
<?php endif; ?>
