<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\CatalogInventory\Block\Stockqty\DefaultStockqty;
use Magento\Framework\Escaper;

/** @var DefaultStockqty $block */
/** @var Escaper $escaper */
?>
<?php if ($block->isMsgVisible()): ?>
    <p class="availability only">
        <?= /* @noEscape */ __('Only %1 left', "<span class='font-bold'>{$escaper->escapeHtml($block->getStockQtyLeft())}</span>") ?>
    </p>
<?php endif ?>
