<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display shipping including and excluding tax -->
<template x-if="segment.code === 'shipping' && quoteData.is_virtual === 0 && !!shippingMethod && 'both' === checkoutConfig.reviewShippingDisplayMode">
    <div :class="wrapperClass">
        <div x-text="`${segment.title} ${excludingTaxMessage}`"></div>
        <div x-text="hyva.formatPrice(totalsData.shipping_amount)" class="justify-self-end"></div>
        <div x-text="`${segment.title} ${includingTaxMessage}`"></div>
        <div x-text="hyva.formatPrice(totalsData.shipping_incl_tax)" class="justify-self-end"></div>
    </div>
</template>

<!-- display shipping excluding tax -->
<template x-if="segment.code === 'shipping' && quoteData.is_virtual === 0 && !!shippingMethod && 'excluding' === checkoutConfig.reviewShippingDisplayMode">
    <div :class="wrapperClass">
        <div x-text="segment.title"></div>
        <div x-text="hyva.formatPrice(segment.value)" class="justify-self-end"></div>
    </div>
</template>

<!-- display shipping including tax -->
<template x-if="segment.code === 'shipping' && quoteData.is_virtual === 0 && !!shippingMethod && 'including' === checkoutConfig.reviewShippingDisplayMode">
    <div :class="wrapperClass">
        <div x-text="segment.title"></div>
        <div x-text="hyva.formatPrice(totalsData.shipping_incl_tax)" class="justify-self-end"></div>
    </div>
</template>
