<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal including and excluding tax -->
<template x-if="segment.code === 'subtotal' && 'both' === checkoutConfig.reviewTotalsDisplayMode">
    <div :class="wrapperClass">
        <div x-html="`${segment.title} (${excludingTaxMessage})`"></div>
        <div x-text="hyva.formatPrice(totalsData.subtotal)" class="justify-self-end"></div>
        <div x-html="`${segment.title} (${includingTaxMessage})`"></div>
        <div x-text="hyva.formatPrice(totalsData.subtotal_incl_tax)" class="justify-self-end"></div>
    </div>
</template>

<!-- display subtotal excluding tax -->
<template x-if="segment.code === 'subtotal' && 'excluding' === checkoutConfig.reviewTotalsDisplayMode">
    <div :class="wrapperClass">
        <div x-html="segment.title"></div>
        <div x-text="hyva.formatPrice(totalsData.subtotal)" class="justify-self-end"></div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="segment.code === 'subtotal' && 'including' === checkoutConfig.reviewTotalsDisplayMode">
    <div :class="wrapperClass">
        <div x-html="segment.title"></div>
        <div x-text="hyva.formatPrice(totalsData.subtotal_incl_tax)" class="justify-self-end"></div>
    </div>
</template>
