<div x-data="initComponent()" class="flex justify-center">
    <div>
        <button @click="toggleDropdown"
                class="bg-gray-200 p-2 border rounded-sm mb-3"> <?= __('Toggle dropdown') ?>  </button>
        <div x-show="open" @click.away="closeDropdown" @click.outside="closeDropdown">
            <?= __('Dropdown content') ?>
        </div>
    </div>
</div>

<script>
    function initComponent() {
        return {
            open: false,
            toggleDropdown() {
                this.open = !this.open;
            },
            closeDropdown() {
                this.open = false;
            }
        };
    }
</script>
