<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Block\SortableItem;
use Magento\Framework\Escaper;

/** @var SortableItem $block */
/** @var Escaper $escaper */
?>

<span id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
      class="delimiter block border-b border-container w-full my-2"
></span>
