<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\Image;
use Magento\Framework\Escaper;

/** @var Image $block */
/** @var Escaper $escaper */
?>
<img
    src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
    width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
    loading="lazy"
    class="photo image <?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
    <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
        <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
    <?php endforeach; ?>
>
