<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Block\Category\View;
use Magento\Catalog\ViewModel\Category\Output as CategoryOutput;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CategoryOutput $categoryOutput */
$categoryOutput = $viewModels->require(CategoryOutput::class);
?>

<?php if ($description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="category-description max-w-4xl">
        <?= /* @noEscape */ $categoryOutput->categoryAttribute($block->getCurrentCategory(), $description, 'description') ?>
    </div>
<?php endif; ?>
