<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var AccountTokens $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Vault\Block\Customer\AccountTokens;

$tokens = $block->getPaymentTokens();

?>
<?php if (count($tokens) !== 0): ?>
<div class="card grid grid-cols-2 mb-4">
    <div class="text-sm p-2"><?= $escaper->escapeHtml(__('PayPal Account')) ?></div>
    <div class="text-sm p-2 text-center">
        <span class="sr-only"></span>
    </div>
    <?php foreach ($tokens as $token): ?>
        <?= /* @noEscape */ $block->renderTokenHtml($token) ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
