<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */

if ($block->isLoggedIn()): ?>
    <?php $dataPostParam = $block->getPostParams(); ?>
    <li class="nav item">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            @click.prevent='hyva.postForm(<?= /* @noEscape */ $dataPostParam ?>)'
        >
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php else: ?>
    <li class="nav item">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif; ?>
