<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var string  $htmlAttributes */
/** @var string  $headAttributes */
/** @var string  $headContent */
/** @var string  $headAdditional */
/** @var string  $bodyAttributes */
/** @var string  $layoutContent */
?>
<!doctype html>
<html <?= /* @noEscape */ $htmlAttributes ?>>
<head <?= /* @noEscape */ $headAttributes ?>>
    <?= /* @noEscape */ $headContent ?>
    <?= /* @noEscape */ $headCritical ?? '' ?>
    <?= /* @noEscape */ $headAssets ?? '' ?>
    <?= /* @noEscape */ $headAdditional ?>
</head>
<body <?= /* @noEscape */ $bodyAttributes ?>>
<?= /* @noEscape */ $layoutContent ?>
</body>
</html>
