<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Shipping\Block\Tracking\Link;

/** @var Escaper $escaper */
/** @var Link $block */

$order = $block->getOrder();
?>
<a href="<?= $escaper->escapeUrl($block->getWindowUrl($order)) ?>" class="underline"
   target="_blank" rel="noopener" title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>">
    <?= $escaper->escapeHtml($block->getLabel()) ?>
</a>
