<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

?>

<div class="gift-summary mb-4" x-show="resultBlockVisibility">
    <div class="additional-options-summary"></div>
    <dl x-show="savedFormMessage.message" aria-describedby="<?= $escaper->escapeHtml(__('Gift Message')) ?>">
        <div>
            <dt class="font-bold inline"><?= $escaper->escapeHtml(__('To:')) ?></dt>
            <dd class="inline" x-text="savedFormMessage.recipient"></dd>
        </div>
        <div>
            <dt class="font-bold inline"><?= $escaper->escapeHtml(__('From:')) ?></dt>
            <dd class="inline" x-text="savedFormMessage.sender"></dd>
        </div>
        <div>
            <dt class="font-bold inline"><?= $escaper->escapeHtml(__('Message:')) ?></dt>
            <dd class="inline" x-text="savedFormMessage.message"></dd>
        </div>
    </dl>
</div>

<div class="flex flex-col gap-6">
    <div x-show="hasActiveOptions">
        <?= $block->getChildHtml('additional-options') ?>
    </div>
    <template x-if="isGiftMsgEnabled">
        <div>
            <?= $block->getChildHtml('gift-message') ?>
        </div>
    </template>
</div>

<div class="actions-toolbar">
    <button type="button" class="btn btn-primary" @click="submitGiftOption">
        <?= $escaper->escapeHtml(__('Update')) ?>
    </button>
    <template x-if="isGiftMsgEnabled">
        <button type="button" class="btn" @click="clearGiftOption">
            <?= $escaper->escapeHtml(__('Clear')) ?>
        </button>
    </template>
    <button type="button" class="btn" @click="closeDialog">
        <?= $escaper->escapeHtml(__('Cancel')) ?>
    </button>
</div>

<?= $block->getChildHtml('loading') ?>
