<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
$childHtml = $block->getChildHtml('', true);
?>
<?php if (strlen($childHtml)): ?>
    <div class="product-options-wrapper" id="product-options-wrapper">
        <div class="fieldset" tabindex="0">
            <?= /* @noEscape */ $childHtml ?>
        </div>
    </div>
<?php endif; ?>
