<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="bg-gray-100 border-t border-gray-300 pb-16">
    <div class="container py-8">
        <div class="flex flex-wrap gap-y-16">
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?= $childName !== 'footer-copyright' ? $block->getBlockHtml($childName) : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="bg-surface border-t border-b border-gray-300">
        <div class="container py-6 flex items-center sm:flex-row flex-col">
            <a href="https://hyva.io" class="text-xl font-medium">Hyvä Theme</a>
            <p><?= $block->getChildHtml('copyright') ?></p>
        </div>
    </div>
</div>

