<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$target_id = $block->getTargetId();
?>
<div id="<?= $escaper->escapeHtmlAttr($target_id) ?>" tabindex="-1"></div>
