<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$target = $block->getTarget();
$label = $block->getLabel();
?>
<a class="action skip sr-only focus:not-sr-only focus:absolute focus:z-40 focus:bg-white
   <?= $escaper->escapeHtmlAttr($target) ?>"
   href="#<?= $escaper->escapeHtmlAttr($target) ?>">
    <span>
        <?= $escaper->escapeHtml($label) ?>
    </span>
</a>
