<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\PageJsDependenciesRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$jsDependencies = $viewModels->require(PageJsDependenciesRenderer::class);

// This $block is also used in \Hyva\Theme\Observer\RegisterPageJsDependencies::applyBlockOutputPatternJsDependencyRules

echo $jsDependencies->getJsDependenciesHtml();
