<script>document.addEventListener('alpine:init', () => {

        Alpine.store('compare', {
            items: [],
            init() {
                window.addEventListener('private-content-loaded', (event) => {
                    const items = event.detail.data['compare-products']?.items || [];
                    this.items = items.map(item => ({
                        id: Number(item.id)
                    }));
                });
            },

            add(id, addToCompare) {
                if (!this.has(id)) {
                    addToCompare(id);
                    this.items.push({id: Number(id)});
                }
            },

            has(id) {
                return this.items.some(
                    item => Number(item.id) === Number(id)
                );
            },

            remove(productId, productName, removeFromCompare) {
                removeFromCompare(productId, productName);

                this.items = this.items.filter(
                    item => Number(item.id) !== Number(productId)
                );
            },

            clear() {
                if (!window.confirm("Are you sure?")) return;

                const postUrl = BASE_URL + 'catalog/product_compare/clear/';
                const formKey = hyva.getFormKey();
                const uenc = hyva.getUenc();

                fetch(postUrl, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    body: "form_key=" + formKey + "&uenc=" + uenc
                })
                    .then(() => {
                        this.items = [];
                        window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
                        window.location.reload();
                    });
            }
        });

        Alpine.store('toast', {
            listItems: [],
            itemsToast: [],

            init() {
                window.addEventListener('messages-loaded', (event) => {
                    this.listItems.push(...event.detail.messages);
                    this.success();

                });
            },
            success() {
                this.listItems.forEach((msg) => {
                    const exists = this.itemsToast.some(
                        item => item.text === msg.text
                    );

                    if (exists) return;

                    const toast = {
                        id: crypto.randomUUID(),
                        ...msg
                    };

                    this.itemsToast.push(toast);
                    setTimeout(() => {
                        this.remove(toast.id);
                    }, 5000);
                });
            },

            remove(id) {
                this.itemsToast = this.itemsToast.filter(
                    item => item.id !== id
                );
            }
        });

        Alpine.store('drawer', {
            isVisibleFilters: false,
            isActiveId: null,
            active: null,
            isMobile: false,
            isSubMenuOpen: false,
            isOverflowing: false,
            init() {
                const mediaQuery = window.matchMedia('(max-width: 767px)');
                this.isMobile = mediaQuery.matches;

                mediaQuery.addEventListener('change', (event) => {
                    this.isMobile = event.matches;
                    console.log(this.isMobile);
                });
            },
            open(name, id) {
                this.active = name;
                if (name === 'filterItems') {
                    this.isVisibleFilters = true;
                }
                if (id) {
                    this.isActiveId = id;
                }
            },
            close() {
                this.active = null;
            },
        })

        Alpine.store('compare').init();
        Alpine.store('toast').init();
        Alpine.store('drawer').init();
    });
</script>
