<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Link $block */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <a @click.prevent.stop="$dispatch('toggle-authentication',
        {url: '<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getCheckoutUrl())) ?>'});"
        href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getCheckoutUrl())) ?>"
        title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
        class="btn btn-primary btn-checkout w-full"
        id="checkout-link-button"
    >
        <?= $escaper->escapeHtml(__('Proceed to Checkout')) ?>
    </a>
<?php endif ?>
