<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Info;

/** @var Info $block */
/** @var Escaper $escaper */
?>

<span class="order-status inline-block px-3 py-3 border rounded border-gray-300">
    <span class="sr-only">
        <?= $escaper->escapeHtml(__('Status')) ?>:&nbsp;
    </span>
    <?= $escaper->escapeHtml($block->getOrder()->getStatusLabel()) ?>
</span>
