<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Magento\Catalog\Model\Product $product */

/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */

use Magento\Framework\Registry;
use Hyva\Theme\ViewModel\LucideIcons;

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);
/** @var Registry $registry */
$registry = \Magento\Framework\App\ObjectManager::getInstance()
    ->get(Registry::class);

$product = $registry->registry('current_product');
$productName = $product->getName();
$productId = (int)$product->getId();
?>
<script>
    function initCompareOnProductView() {
        return {
            addToCompare(productId) {
                fetch(BASE_URL + 'catalog/product_compare/add/', {
                    headers: {'content-type': 'application/x-www-form-urlencoded; charset=UTF-8'},
                    body: 'form_key=' + hyva.getFormKey() + '&product=' + productId + '&uenc=' + hyva.getUenc(),
                    method: 'POST', mode: 'cors', credentials: 'include'
                }).then(r => {
                    if (r.redirected) { window.location.href = r.url; return; }
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            }
        }
    }
</script>
<button x-data="initCompareOnProductView()"
        @click.prevent="addToCompare(<?= (int)$productId ?>)"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare') . ' ' . $productName) ?>"
        type="button"
        class="btn p-2 rounded-full hover:text-red-400"
        :class="$store.compare.has(<?= (int)$productId ?>)
    ? 'border-[1px] border-red-400' : 'border-transparent'" data-addto="compare"
>
    <?= $lucideIcons->scaleHtml("", 20, 20, ['aria-hidden' => 'true']) ?>
</button>
