<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$wishlistViewModel = $viewModels->require(Wishlist::class);
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $currentProduct->get();

if (!$product->getId() || !$wishlistViewModel->isEnabled()) {
    return;
}
?>

<button x-data="initWishlist(<?= (int)$product->getId() ?>)"
        x-init="init()"
        @click.prevent="toggleWishlist()"
        :disabled="isLoading"
        :title="isActive ? '<?= $escaper->escapeHtmlAttr(__('Remove from Wishlist')) ?>' : '<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>'"
        id="add-to-wishlist"
        class="btn p-2 rounded-full ml-4 transition-colors"
        :class="isActive ? 'text-red-600' : 'text-gray-400 hover:text-red-400'"
>    <span class="text-sm text-gray-600"><?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?></span>
    <span>
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" :fill="isActive ? 'currentColor' : 'none'"
             stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
             viewBox="0 0 24 24"><path
                d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"/></svg>
    </span>
</button>
