<ul>
    <li class="col label w-1/2 py-2 text-left text-fg-secondary font-normal product-attribute-label"> <?= __('Fast delivery') ?> </li>
    <li class="col label w-1/2 py-2 text-left text-fg-secondary font-normal product-attribute-label"> <?= __('Pay on delivery') ?>
    </li>
    <li class="col label w-1/2 py-2 text-left text-fg-secondary font-normal product-attribute-label"> <?= __('Easy returns') ?></li>
</ul>

