<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\View\Element\Template;

/** @var HyvaCsp $hyvaCsp */
/** @var Template $block */

// Bypass waiting for user interaction for pages where external script loading is critical.
// e.g., running analytics/conversion scripts on the order success page.
?>
<script>
    window.dispatchEvent(new Event('init-external-scripts'));
</script>
<?php $hyvaCsp->registerInlineScript() ?>
