<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();

?>

<h2 class="mb-6 text-2xl text-center md:text-left">
    <?= $escaper->escapeHtml(__('Description')) ?> /
    <span class="font-semibold"><?= $escaper->escapeHtml($product->getName()) ?></span>
</h2>
