<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<div x-data="initGetFreeShipping()" x-init="init()"
     class="ml-auto">

    <template x-if="!free">
        <div class="ml-auto mb-4">
            <div class="flex items-center gap-2 mb-2">
                <div class="w-64 p-1 h-4 border border-black bg-gray-100 rounded-sm">
                    <div class="bg-gray-900 p-1  h-full" :style="`width:${progress}%`"></div>
                </div>
                <p class="text-sm text-gray-800 leading-tight tracking-wide" x-text="Math.floor(progress) + '%'"></p>
            </div>
            <span
                class="text-sm text-gray-800 leading-tight tracking-wide"
                x-text="'<?= $escaper->escapeJs(__('You are %1 away from free shipping')) ?>'
        .replace('%1', '$' + remaining)"
            ></span>
        </div>
    </template>

    <template x-if="free">
        <p class="py-2 text-sm text-gray-800 leading-tight tracking-wide"
           x-text="'<?= $escaper->escapeJs(__('You have free shipping!')) ?>'"></p>
    </template>
</div>
