<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\LucideIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);
?>

<a x-data x-show="$store.compare && $store.compare.items.length > 0"
   id="compare-link"
   class="relative md:inline-flex btn bg-transparent border-transparent p-1 "
   x-cloak
   href="<?= $escaper->escapeUrl($block->getUrl('catalog/product_compare/index')) ?>"
   title="<?= $escaper->escapeHtmlAttr(__('Compare Products')) ?>">

    <?= $lucideIcons->scaleHtml('', 24, 24, ["aria-hidden" => "true"]) ?>
    <span
        x-text="$store.compare.items.length"
        class="absolute -top-1.5 -right-1.5 px-2 py-1 rounded-full bg-primary text-on-primary
            text-xs font-semibold leading-none text-center uppercase tabular-nums"
        aria-hidden="true"
    ></span>
</a>
