<?php
/** @var ViewModelRegistry $viewModels */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Modal;

$heroicons = $viewModels->require(HeroiconsOutline::class);
$modalViewModel = $viewModels->require(Modal::class);

/**
 * MAIN MODAL
 */
$modal = $modalViewModel
    ->createModal()
    ->withDialogRefName('popup-dialog')
    ->withContent(content: '
        <div class="w-full max-w-xl md:h-auto">

           <div class="flex justify-end">
        <button @click="hideModal" class="flex justify-end z-10 font-600">
            X
        </button>
    </div>

            <div class="p-6 space-y-4">
                  <h2 class="text-lg font-semibold">
                    What is Lorem Ipsum?
                </h2>

                <p class="text-sm text-gray-700">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    It has been the industry\'s standard dummy text.
                </p>

                <button
                    type="button"
                    class="px-4 py-2 rounded bg-blue-600 text-white hover:bg-blue-400 mb-2"
                    @click="openNestedModal"
                >
                    Open nested modal
                </button>
            </div>

        </div>
    ')
    ->addDialogClass('w-full sm:w-1/2 lg:w-1/3 p-2');


/**
 * NESTED MODAL
 */
$nestedModal = $modalViewModel
    ->createModal()
    ->withDialogRefName('nested-popup-dialog')
    ->withContent('
        <div class="w-full max-w-xl md:h-auto">

             <div class="flex justify-end">
        <button @click="closeNestedModal" class="flex justify-end z-10 font-600">
            X
        </button>
    </div>

            <div class="p-6 space-y-4 text-slate-950">
                <h2 class="text-lg font-semibold">
                    Nested modal
                </h2>

                <p class="text-sm text-white-700">
                    This is nested modal content with proper stacking.
                </p>
            </div>

        </div>
    ')
    ->addDialogClass('w-full sm:w-1/2 lg:w-1/3 p-2');
?>

<div
    x-data="{
        showModal: false,
        showNestedModal: false,

        openModal() {
            this.showModal = true;
        },

        hideModal() {
            this.showModal = false;
        },

        openNestedModal() {
            this.showNestedModal = true;
        },

        closeNestedModal() {
            this.showNestedModal = false;
        }
    }"
>
    <button
        type="button"
        class="px-4 py-2 rounded bg-blue-600 text-white hover:bg-blue-400 mb-2"
        @click="openModal"
    >
        Open modal
    </button>

    <template x-if="showModal">
        <?= $modal ?>
    </template>

    <template x-if="showNestedModal">
        <?= $nestedModal ?>
    </template>
</div>
