<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Shopping cart additional info
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php
//$block->getChildHTML();
$name = $block->getNameInLayout();
foreach ($block->getChildNames($name) as $childName) {
    // phpcs:ignore Magento2.Security.LanguageConstruct.DirectOutput
    echo $block->getChildBlock($childName)->setItem($block->getItem())->toHtml();
}
?>
