<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Block\Adminhtml\Page\Footer;
use Magento\Framework\Escaper;

/** @var Footer $block */
/** @var Escaper $escaper */

?>

<p class="magento-version hyva-version">
    <strong><?= $escaper->escapeHtml(__('Hyvä Theme Module')) ?></strong>
    <?= $escaper->escapeHtml(__('ver. %1', $block->getVersion())) ?>
</p>
