<?php
/** @var \Hyva\Theme\ViewModel\Modal $modalViewModel */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\Modal $modalViewModel */

$modalViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Modal::class);
$productBtn = $escaper->escapeHtml(__('Apply'));
$modalTitle = $escaper->escapeHtml(__('Enter promo code'));
?>

<div x-data="hyvaModal">

    <button
        @click="show('modal12')"
        type="button"
        class="btn bg-blue-600 text-white text-sm mb-3 hover:bg-blue-400"
        aria-haspopup="dialog"
    >
        <?= $escaper->escapeHtml(__('Apply Discount Preview')) ?>
    </button>

    <?= $modalViewModel->createModal()
        ->withDialogRefName('modal12')
        ->withContent('<div x-data="initGetPromo()" class="relative">
    <button @click="hide" type="button" class="absolute top-0 right-0 text-gray-600 hover:text-gray-900 text-3xl font-bold leading-none w-10 h-10 flex items-center justify-center z-50 cursor-pointer">×</button>
    <h3 class="text-lg font-semibold mb-4 pr-12">' . $modalTitle . '</h3>
    <form @submit.prevent="$dispatch(\'save-promo-code\', {promocode: promocode}); if(!errorMessage){hide()}">
        <input type="text" name="promoCode" x-model="promocode" class="input-text w-full mb-3 px-4 py-2 border border-gray-300 rounded" placeholder="' . $modalTitle . '" />
        <p x-text="errorMessage" x-show="errorMessage" class="text-sm text-red-500 mb-1"></p>
        <button type="submit" class="button py-2 px-4 rounded-sm bg-blue-600 hover:bg-blue-700 text-white text-sm block mx-auto w-full">'
            . $productBtn .
            '</button>
    </form>
</div>')
        ->positionCenter()
        ->withAriaLabelledby('the-label')
        ->addDialogClass('rounded', 'bg-white')
    ?>

</div>
