<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $hyvaicons */

$hyvaicons = $viewModels->require(SvgIcons::class);
?>
<template x-if="isLoading">
    <div class="z-10 absolute w-full h-full flex items-center justify-center bg-white/60">
        <?= $hyvaicons->renderHtml('loader', '', 20, 20, ['aria-hidden' => 'true']); ?>
    </div>
</template>

