<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>
<?php if ($block->getWishlist()->getItemsCount() &&
    $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
    <button type="submit"
            name="save_and_share"
            title="<?= $escaper->escapeHtmlAttr(__('Share Wish List')) ?>"
            class="action share btn btn-secondary">
        <span>
            <?= $escaper->escapeHtml(__('Share Wish List')) ?>
        </span>
    </button>
<?php endif;?>
