<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<?php if ($childrenHtml = $block->getChildHtml()): ?>
    <div class="flex flex-wrap gap-8 pr-4 w-full lg:w-1/4 md:w-1/2">
        <?= /** @noEscape */ $childrenHtml ?>
    </div>
<?php endif; ?>
